name: elm-gcc-formatter
version: "0.1"

dependencies:
  - base
  - aeson
  - string-conversions
  - filepath
  - getopt-generics

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec

executables:
  elm-gcc-formatter:
    main: Main.hs
    source-dirs:
      - src
